### ISSUE TITLE
Git tag for 0.3.12 missing?

### ISSUE THREAD

**Issue by hartwork** [eddyxu/cpp-coveralls#112]
Hi!

Using pip I get 0.3._12_ installed but I cannot find that on GitHub (https://github.com/eddyxu/cpp-coveralls/tags), saying 0.3._11_ to b the latest. Did you forget to push that tag?

Best, Sebastian

**Comment by hartwork** [comment]
Hi! Why close the ticket without pushing a Git tag? At least I don't see any on https://github.com/eddyxu/cpp-coveralls/tags.

**Comment by eddyxu** [comment]
Oh, sorry. Forgot to push.  Now there is one `v0.3.12`

**Comment by hartwork** [comment]
Nice, thank you!
