### ISSUE TITLE
pkg_resources.UnknownExtra: urllib3 1.7.1 has no such extra feature 'secure'

### ISSUE THREAD

**Issue by ColinDuquesnoy** [eddyxu/cpp-coveralls#118]
I am running into [this issue](https://travis-ci.org/ColinDuquesnoy/MellowPlayer/jobs/258836742#L1240) when running cpp-coveralls on travis-ci (Trusty) with ``language`` set to ``cpp`` and python 2 installed using ``sudo apt-get install python`` (python 2.7.5).

I think this is related to PR #109.

My temporary workaround is to install ``cpp-coveralls<0.4.0``.

Any idea what is going on and how to resolve this issue?

**Comment by eddyxu** [comment]
Bummer. From the error in [travis](https://travis-ci.org/ColinDuquesnoy/MellowPlayer/jobs/258836742#L1235), It is due to the old python 2 version. 

> /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.

Let me see what I can do.

**Comment by eddyxu** [comment]
@ColinDuquesnoy Can you try to run "pip install -U cpp-coveralls"?

**Comment by jdm64** [comment]
Fix worked for me.

**Comment by ColinDuquesnoy** [comment]
Yes it works. Thank you!

**Comment by zorosmith** [comment]
It works
