### ISSUE TITLE
Travis CI keeps erroring

### ISSUE THREAD

**Issue by Droobledores** [eddyxu/cpp-coveralls#123]
[Here](https://github.com/AnimationNerds/pencil/commit/9a53ee024e2157cb293267cd4301d0d9c2c5efb6) is the link to the commit that is causing the problem

**Comment by mkfifo** [comment]
Can you please provide more information such as a link to the failing travis

**Comment by eddyxu** [comment]
I will close this given that there is no more information provided. Please feel free to reopen it.
