### ISSUE TITLE
Can't run coverage on travis

### ISSUE THREAD

**Issue by crondaemon** [eddyxu/cpp-coveralls#64]
Hi 
I followed your instructions to run the code coverage on github, but it doesn't work.

https://travis-ci.org/crondaemon/dines/builds/33904246

I made many tries, but no luck. If I run cpp-coveralls from my local copy, it works fine.
Any Idea?

**Comment by kevingranade** [comment]
Just for searchability, another symptom of this mismatch is out of memory errors, see the end of the build here: https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/240641468
