### ISSUE TITLE
--exclude/--exclude-pattern can't be used at the same time as --include

### ISSUE THREAD

**Issue by dsvensson** [eddyxu/cpp-coveralls#70]
When passing --include, all --exclude/--exclude-pattern parameters are ignored and file matching only considers if a file is in any of the include paths or not.

The following seems like a pretty valid usecase that would be nice if it was supported:

    coveralls --include src --exclude src/not-this-file.c --exclude-pattern '.*useless.*'

**Comment by eddyxu** [comment]
@dsvensson Thanks for reporting this.

This bug should be fixed in e9dceb8829dc8bf5bbb05313a4be24a7e9485523.

**Comment by dsvensson** [comment]
I see that I was vague in my bug report. The committed fix is inclusive.
The following:

    --include src/foo
    --include src/bar
    --exclude-pattern '.*useless.*'
    --exclude src/foo/hey.c

Will happily include 'src/baz/*' files as well, while I see the parameters as all constraining:

    intersection(
        intersection($universe,
            union(match(src/foo), match(src/bar))
        ),
        complement(
            union(match(.*useless.*), match(src/foo/hey.c))
        )
    )

Which would match files in src/foo, and src/bar, and from that match, prune everything that matches .*useless.* and src/foo/hey.c.
