### ISSUE TITLE
Version 0.3.3 doesn’t install with easy_install on OS X 10.10

### ISSUE THREAD

**Issue by 0xced** [eddyxu/cpp-coveralls#72]
Since version 0.3.3, installing cpp-coveralls on Travis-CI [doesn’t work anymore](https://travis-ci.org/0xced/XCDYouTubeKit/builds/49573058). It used to [work fine](https://travis-ci.org/0xced/XCDYouTubeKit/builds/49292358) with previous versions.

It looks like a packaging problem to me but I’m not familiar enough with python package management to fully understand what’s happening.

**Comment by eddyxu** [comment]
@0xced It was due to my mistakenly upload a binary package. I deleted it now. It should be resolved.
