### ISSUE TITLE
Files without code (header) are reported as 0% covered

### ISSUE THREAD

**Issue by krocard** [eddyxu/cpp-coveralls#76]
In coverall, files without any code are listed with a red 0% coverage even though there is no code to cover!

Some header do not have any code, thus are adding lots of noise information in the coveralls report: the beginning of the report is flooded by 0% covered headers.
It has 3 consequences:
 - a negative impression (lots of files uncovered even if they have no code)
 - the need to search for non 0 code line files in the list.
 - code coverage drop (pull request warning) on the removal of all function definition of a header (eg: if a header contains one function definition and a pull request moves it to the .cpp, a red warning will be displayed by coveralls as this header coverage will drops from 100% to 0%).

In c++, header usually have a small (sometime big) amount of code so they can *not* be excluded from coveralls (eg: with `--exclude`). 

Would it be possible to report files without any code as 100% covered ?

**Comment by krocard** [comment]
The problem was that gcov was first run without the -p (preserve-paths) option by the build system and then with the option by cpp-coveralls. As a result 2 types of .gcov were generated: with and without full path, this seems to confuse cpp-coveralls.

**Comment by krocard** [comment]
The issue is still present, I was looking at the CHANGED tab instead of the ALL tab. All 0 code headers are still marked at 0%.

**Comment by MartinDelille** [comment]
:+1:

**Comment by krocard** [comment]
**TLTR:** cpp-coveralls is not to blame, it is the [server](http://coveralls.io) that needs to be fixed.


cpp-coveralls sends only covered and uncovered lines, it is [coveralls server](http://coveralls.io) that calculates the coverage ration per file.

Running cpp-coveralls on a toy example: 
~~~ {Dockerfile}
FROM ubuntu
RUN apt-get update
RUN apt-get install -y python-pip gcc git
RUN pip install cpp-coveralls
WORKDIR /home

RUN echo 'class C {}; '              > empty.hpp
RUN echo 'int f() { return 0; }'     > main.hpp
RUN echo '#include "empty.hpp"'      > main.cpp
RUN echo '#include "main.hpp"'      >> main.cpp
RUN echo 'int main() { return 0; }' >> main.cpp
RUN g++ --coverage main.cpp && ./a.out
RUN coveralls --dryrun --verbose --gcov-options '\-lp'
~~~
Outputs (after formating) :
~~~ {python}
{ 'service_name': 'travis-ci',
  'git': {...},
  'source_files': [
    {'source': u'int f() { return 0; }\n',
               'name': 'main.hpp', 'coverage': [0]},
    {'source': u'#include "main.hpp"\n int main() { return 0; }\n',
               'name': 'main.cpp', 'coverage': [None, 1]}],
    {'source': u'class C {}; \n',
               'name': 'empty.hpp', 'coverage': [None]}],
  'service_job_id': ''}
}
~~~

As you can see each line has a corresponding coverage: the number of time executed or `None` if it is not an executable line.
See the [official api documentation](https://coveralls.zendesk.com/hc/en-us/articles/201774865-API-Introduction) for more information about coveralls post format.

A file with 0 code line will be reported as a list of `None` not as a *0%* or *100%* covered file. As a result this issue can not be fix in cpp-coveralls. The statistic generator (on coveralls server) has to change it's coverage rate algorithm.

**Comment by krocard** [comment]
I sent an email to coveralls.io. I hope they will be able to change this annoying behaviour.

**Comment by eddyxu** [comment]
@krocard  Sorry for the late reply. This is a awesome work. Thank you so much!

**Comment by krocard** [comment]
Thanks @eddyxu, I hope it will motivate coveralls to address this issue.

**Comment by krocard** [comment]
It seems that it is now fixed. [coveralls](http://coveralls.io) now correctly displays 0 relevant line files as 100% covered!
