### ISSUE TITLE
cpp-coveralls should respect environmental variable COVERALLS_REPO_TOKEN

### ISSUE THREAD

**Issue by mkfifo** [eddyxu/cpp-coveralls#77]
This is particularly useful in environments such as travis-ci as you can trivially set secure env variables

**Comment by mkfifo** [comment]
This config variable is mentioned here https://coveralls.zendesk.com/hc/en-us/articles/201347419-Coveralls-currently-supports

**Comment by mkfifo** [comment]
My particular use case is a public git repo using travis-ci (free), I need a way of specifying the token that cannot be seeing by inspecting either my repo or my travis-ci output.

Travis-ci allows you to securely specify environmental variables that are not exposed in your log output.

**Comment by mkfifo** [comment]
Made a new pull request as I had my author email set incorrectly to my work address, sorry for the noise.

**Comment by eddyxu** [comment]
Thanks for working on it!

**Comment by mkfifo** [comment]
This also nicely being cpp-coverals inline with https://github.com/mkfifo/python-coveralls#configuration
