### ISSUE TITLE
Container builds on travis and cpp-coveralls

### ISSUE THREAD

**Issue by drewpts** [eddyxu/cpp-coveralls#92]
Hello.
How can I build and install coveralls to user-specified directory? I haven't seen such options on install script.

Moreover what should I do for using coveralls on travis-ci with container-builds? With containers I can't run `sudo easy_install3 cpp-coveralls` anyway, because sudo is disabled.

Thanks.

**Comment by eddyxu** [comment]
Hi, @drewpts 

You can use ```pip install --user`` to install it into your home directory.

**Comment by drewpts** [comment]
Thanks, @eddyxu !
