### ISSUE TITLE
cpp-coveralls & coveralls-python

### ISSUE THREAD

**Issue by FrancescElies** [eddyxu/cpp-coveralls#94]
I am using the merge functionality from https://github.com/coagulant/coveralls-python to get c code and python code reported at coveralls.

The problem I am facing is that `pip install cpp-coveralls` & `pip install coveralls` are called coveralls from the command line, I believe, I need both packages to get c and python code covered together, but since both are called through the same name makes the whole a bit inconvenient, does anybody see a solution for this?

**Comment by mkfifo** [comment]
As a work around you can consider:

As long as they have unique paths then you should be able to call them via `/bar/coveralls` and /foo/coveralls`, `pip` supports a `--target` option to allow you to specify the install path.
see https://pip.pypa.io/en/latest/reference/pip_install.html#options

So something like:
```
# untested code
mkdir cpp-coveralls
mkdir coveralls
pip install --target cpp-coveralls cpp-coveralls
pip install --target coverals coveralls
./cpp-coveralls/coveralls
./coveralls/coveralls
# do a merge here.
```

**Comment by FrancescElies** [comment]
Hi,

thanks for your quick reply, I'll give it a try.
